[project]
name = "vk-captcha-solver-py"
version = "0.1.0"
description = "VK Captcha Solver ported to Python"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "requests>=2.31.0",
    "pillow>=10.0.0",
    "numpy>=1.26.0",
    "aiohttp>=3.13.2",
    "vkbottle",
]

[tool.uv.sources]
vkbottle = { git = "https://github.com/50Bytes-dev/vkbottle.git", rev = "bdc00ebb3bc885d89356a9dbcdeba9ad3df9382b" }

[dependency-groups]
dev = ["notebook>=7.5.0"]
